georust/proj

.travis.yml
CHANGES.md
Cargo.toml
README.md
src/proj.rs

Also perform an `fmt` and Clippy run

Bump Geo-types to 0.2

---

src/proj.rs

Without resetting errno, any previous errors will persist, causing
all future calls to convert() or project() to fail

Call proj_errno_reset before convert or project

---

Cargo.toml
src/proj.rs

Hi, I ran over one typo in one of the test and as I was fixing it, I realize 2 tests were ignored so I decided to propose a fix for it. Hope this helps.
Questions:
- I'm not sure my PR target the correct branch (`master`) please let me know if I need to retarget (and possibly rebase the PR)
- Who should merge the PR? Should it be me or is there a team of official contributors that will take care of it?

Fix some documentation tests

---

Cargo.toml
src/lib.rs
src/proj.rs

Anything that implements `Into<Point<T>>`

Allow more input types

---

CHANGES.md
Cargo.toml
src/lib.rs
src/proj.rs

Add project_array method

---

.travis.yml
CHANGES.md
Cargo.toml
README.md
src/lib.rs

See previous discussion in #26.

Enable bundled_proj and pkg_config features

---

.travis.yml
src/proj.rs

enable network test for ci

---

src/lib.rs

fix docsrs build with correct syntax for crate attribute

---

.github/workflows/test.yml

I pushed up some new container tags based on: https://github.com/georust/docker-images/pull/7

update rust for CI

---

Cargo.toml
proj-sys/CHANGES.md
proj-sys/Cargo.toml

`proj` needs a `proj-sys` with the `bundled_proj_tiff` feature.

Update proj-sys version

---

Cargo.toml
README.md
proj-sys/Cargo.toml
proj-sys/README.md
proj-sys/build.rs
src/lib.rs

Update to PROJ 7.2.1

---

.github/workflows/test.yml

See https://github.com/georust/docker-images/pull/11 for more details and discussion.

test on multiple rust versions

---

CHANGES.md
Cargo.toml
proj-sys/CHANGES.md
proj-sys/Cargo.toml

release: proj-0.22.1, proj-sys-0.19.1

---

CODE_OF_CONDUCT.md
README.md
proj-sys/MAINTAINERS.md
proj-sys/build.rs
src/lib.rs
src/proj.rs

* readme links did not work, fixed them with absolute URLs

Spelling, grammar, and fix URL links

---

.gitignore
src/network.rs
src/proj.rs
src/transform.rs

* cargo fmt
* cargo clippy
* added .idea to gitignore

make clippy happy

---

Cargo.toml
proj-sys/Cargo.toml

Followup to #123, we also need to release proj-sys,

bump proj-sys

---

src/lib.rs

I thought I did this last time but apparently not.

Correct requirement details

---

CHANGES.md
Cargo.toml
src/network.rs

This fixes #163, which seems to be related to ARM platforms: https://github.com/ogham/exa/issues/887

Infer pointer cast, bump geo-types

---

CHANGES.md
Cargo.toml

Prepare for 0.27.1 release

---

src/lib.rs

Revert "Add a failing test to check that merge queues work"

---

src/lib.rs

Revert "Take #2: Add a failing test to check that merge queues work"

---

src/lib.rs

Hopefully CI won't merge this.
This time I enabled the "require PR" in the branch protection rules.

Add a failing test to check that merge queues work (#171) (#173)

---

Cargo.toml
proj-sys/CHANGES.md
proj-sys/Cargo.toml

Anything else you want to get in?

prepare for proj-sys 0.25.0 release

---

.github/workflows/test.yml
CHANGES.md
Cargo.toml

Update the MSRV to 1.81 and the edition to 2021

---

CHANGES.md
Cargo.toml

Prepare for 0.29.0 release
