.travis.yml, Cargo.toml, src/lib.rs, src/proj.rs
This PR (also related to #3) updates the version number of the `geo` crate and adds the `num_traits` crate as a dependency, so this should allow for better integration with the `geo` crate.
By the way, I don't know what is the best pattern to follow in this kind of cases (so I don't particularly advocate this solution), but is it really necessary to use the type `geo::Point` as input / output for the `Proj::project` method?
This involves adding the "geo" crate to a project only to use this function (while it might take as input / output something like `(f64, f64)` or `Vec<f64>` ; that's what I did on [another branch](https://github.com/mthh/rust-proj/blob/withoutgeo/src/proj.rs#L56) for a project not using the `geo` crate for now).
=> Bump dependency version

Cargo.toml, README.md, src/lib.rs, src/proj.rs
- specify `proj.4`, now that `proj.5` has been released
- Update dependencies
- Replace use of tuples (not layout-safe for FFI) with `c_void`
- Add rudimentary inline docs
- Add example from tests to README
=> Updates to bindings and docs

.travis.yml, CHANGES.md, Cargo.toml, LICENSE-APACHE, LICENSE-MIT, README.md, src/lib.rs, src/proj.rs
With the surprising release (after about 23 years) of proj.4 v5, and my blowing-the-cobwebs-off PR from yesterday (#5), I thought I'd publish a [`proj-sys`](https://crates.io/crates/proj-sys) crate (generated using `bindgen`), and use it as the basis for this.
Currently, the API contains a very breaking change, because proj.4 performs operations differently now: it distinguishes between _projection_ (conversions from geodetic to projected coordinates) and _conversion_ (conversions between projected coordinate systems, usually within the same datum / reference frame). The latter uses a concept proj.4 calls the [`pipeline`](http://proj4.org/operations/pipeline.html), which allows for multi-step operations to achieve almost any kind of conversion, as opposed to the old system, which only …
=> Move to proj-sys and proj.4 v5

Cargo.toml, src/proj.rs
See discussion at #8 
Error taken from
https://github.com/OSGeo/proj.4/blob/master/test/gie/4D-API_cs2cs-style.gie#L194
5.0.1 now accepts certain nonsensical input, but returns inf, inf
instead of an error. See: https://github.com/OSGeo/proj.4/issues/992#issuecomment-388546006
=> Create valid error

.travis.yml, CHANGES.md, Cargo.toml, README.md, src/lib.rs, src/proj.rs
PROJ.4 v6.0.x has been released and is widely available. Notably, it has support for EPSG strings (and much more besides) for defining conversions, so PROJ strings are no longer needed for many operations.
=> Update to PROJ.4 6.0.0

src/proj.rs
While I didn't add a test for this issue, here's how you can reproduce the problem:
```rust
#[test]
fn test_drop() {
// construct and drop 2000 instances to check for leaks
for _x in 0..1200 {
let _proj = Proj::new(
"+proj=geos +lon_0=0.00 +lat_0=0.00 +a=6378169.00 +b=6356583.80 +h=35785831.0",
)
.unwrap();
}
}
```
On my linux machine I have a limit of 1024 open FDs.  By constructing 1200 Proj objects, but not property destroying them, I end up with errors opening proj.db ("Too many open files")
=> Destroy the threading context object when dropping Proj

CHANGES.md, Cargo.toml, src/lib.rs, src/proj.rs
When transforming between two known CRS, input and output
coordinate order is now normalised to Lat, Lon / Easting Northing.
Note that this normalisation step is only applied to conversion operations between two known CRS (e.g. those that call [proj_create_crs_to_crs](https://proj.org/development/reference/functions.html#c.proj_create_crs_to_crs)), as per the PROJ API.
=> Normalise input and output coordinate order

CHANGES.md, Cargo.toml
First potential contribution to a Rust library.
I've been using the geo, geojson and now the proj crate but I've found there is a conflict of version. Proj is using an older version as I'm getting an error which says `perhaps two different versions of crate geo_types are being used?`
=> Updated Cargo.toml to use the latest version of 'geo-types'

CHANGES.md, Cargo.toml, src/proj.rs
`info` returns information about the current Proj instance, such as the
version and current resource file search path.
`set_search_paths` adds a new path to the existing resource file search paths.
=> Add info and search path modification methods

CHANGES.md, Cargo.toml, README.md, src/lib.rs, src/proj.rs
This is a breaking change (`info()` and `def()` now return `Result`, hence the semver bump), but this PR removes all instances of `unwrap()` in the crate. Other fun additions include making the error enum public for doc purposes, and annotating the errors where useful.
=> More robust error handling

CHANGES.md, Cargo.toml, README.md, src/lib.rs, src/network.rs, src/proj.rs
Uses `reqwest` and the network callback functionality provided by `libproj`.
=> Enable native network functionality without requiring libcurl

.travis.yml, Cargo.toml, src/proj.rs
This enables a statically-linked version of libproj when the
bundled_proj feature is selected.
=> Bump proj-sys to v0.18.0

CHANGES.md, Cargo.toml, src/network.rs, src/proj.rs
These include dependencies which require OpenSSL, which we wish to avoid.
=> Remove default features from reqwest

.travis.yml, Cargo.toml, README.md, src/lib.rs, src/proj.rs
The network stuff adds quite a bit to proj dependencies and build times.
Considering the developer has to opt in to networking anyway by calling enable_network on the context, what would you think about making them jump through one more hoop to make things better for the default user?
With reqwest: builds 166 crates
```
cargo build --release --features network
1019.33s user 22.84s system 658% cpu 2:38.36 total
```
Without reqwest: builds 81 crates
```
cargo build --release  
446.73s user 9.64s system 670% cpu 1:08.02 total
```
If you think it's a good idea, I can open a PR to plumb this feature through geo.
dependency tree:
```
proj v0.20.3 (/Users/mkirk/src/georust/proj)
├── geo-types v0.6.0
│   ├── approx v0.3.2
│   │   └── num-traits v0.2.12
│   │       [build-dependencies]
│   │ …
```
=> Put reqwest behind optional network feature

.github/workflows/test.yml, bors.toml
Can we just use the overall workflow name? Or do we need to enumerate
job names? There are a lot of job names...
=> try to fix bors

.github/workflows/test.yml, Cargo.toml, README.md, src/geo_types.rs, src/lib.rs, src/proj.rs
It seems like the potential users of proj would include people who don't need/want to opt into the whole `geo` ecosystem.
What would you think about having the proj interface be trait-based and having the geo-integration be a feature?
If this seems like a reasonable direction, before merging I'd like to update the docs to show:
1. how you can use this with the greater `geo` ecosystem
2. how you can `impl` your own point type if you're not using geo.
3. how you can use the built-in `(Float, Float)` impl
WDYT @urschrei?
=> proj w/o geo

proj-sys/Cargo.toml, proj-sys/build.rs, src/proj.rs
This was needed to get things compiling on Apple Silicon.
https://github.com/rust-lang/rust-bindgen/blob/master/CHANGELOG.md
=> Upgrade bindgen.

Cargo.toml, src/proj.rs
My suspicion is that creating the raw pointer in the function call was causing it to be dropped prematurely, resulting in garbage data. See [here](https://doc.rust-lang.org/std/ffi/struct.CString.html#method.as_ptr) for an analogous issue when getting a `CString` pointer. We avoid this by explicitly creating the pointer before the call. In addition, the doctest has been updated with a less complex example that doesn't use a proj string.
=> Fix array conversion

Cargo.toml, README.md, proj-sys/src/lib.rs, src/geo_types.rs, src/lib.rs, src/proj.rs
Gives output like:
```
assert_relative_eq!(t.x(), 1450880.29)
left  = 0.0
right = 1450880.29
```
vs previously:
```
thread 'proj::test::test_london_inverse' panicked at 'assertion failed: f > 0.99999', src/proj.rs:885:9
```
=> use `approx` for better failure output

.github/workflows/test.yml, CHANGES.md, Cargo.toml, proj-sys/Cargo.toml, proj-sys/README.md, proj-sys/build.rs
Thoughts? Would be a breaking change since it defaults to not building with TIFF support, and it used to
=> Add feature to configure building with TIFF support.

CHANGES.md, Cargo.toml, src/geo_types.rs, src/network.rs, src/proj.rs
This bumps `geo-types` to v0.7.0 and `reqwest` to v0.11.0 (the latter is a breaking change so we're bumping the minor version too.
=> Bump dependencies

src/network.rs, src/proj.rs
Closes https://github.com/georust/proj/issues/64
=> Add Debug implementation for proj::Proj

CHANGES.md, proj-sys/build.rs
The proj CMakeLists.txt contains instructions to add a `_d` suffix to the compiled library in certain situations:
https://github.com/OSGeo/PROJ/blob/e3d7e18f988230973ced5163fa2581b6671c8755/src/CMakeLists.txt#L86
Proj-sys does not expect this suffix and fails to find the library. This results in build failure.
This PR adds support for the suffixed library.
=> Fix linker error when building proj-sys in debug mode with MSVC

Cargo.toml, proj-sys/Cargo.toml, proj-sys/build.rs
Slightly improves the situation at #57
On apple platforms, libtiff is not installed by the operating system. If
the user has it installed, likely it was installed by homebrew.
Previously, on x86, homebrew installed libs into /usr/lib which is in
the default search path, but since aarch64, homebrew has moved libs to
/opt/homebrew/lib.
So now we use pkg-config to find the library.
Potential problems:
- Not everyone has pkg-config (e.g windows users, a few mac users)
- Not everyone actually needs libtiff, only the network geotiff users,
but we assume everyone needs it since most system installations
include it.
Note that proj enables tiff support by defeault, provided libtiff is
found (using pkg-config? or something else?)
This is a draft because some tests are currently failing for me on …
=> Fix source build on aarch64/homebrew

CHANGES.md, src/network.rs
This a draft PR to investigate the possibility of improving the safety of the `network` functionality.
ATM, this is just a move of the pointer-reconstitution logic into a `Drop` impl (This is safer than assuming a function will be called, although of course `drop()` isn't called on panic), but there will hopefully be more to come when I've done some more digging.
This also fixes some unnecessary mutability and borrows, and makes the struct we pass to libproj `repr c`.
=> Impl drop for HandleData

src/proj.rs
These mutate the underlying context and should be marked appropriately.
=> Mark mutable methods with `&mut`.

src/lib.rs, src/proj.rs
Surface the underlying error from PROJ.
=> Update `proj::Proj` constructors to return `Result` instead of `Option`.

src/proj.rs
~Depends on https://github.com/georust/proj/pull/98~
Needed for https://github.com/georust/geo/pull/718
=> Add TryFrom impls for Proj

src/proj.rs
* Create an `Errno` struct to wrap an errno result from PROJ C calls
* Extract pointer logic from `proj_create*` calls into `result_from_create` function
* Assume PROJ will always give us valid string errors– panic if PROJ doesn't and remove `ProjErrorMessageUtf8Error`, panic
=> Refactor `proj_create*` calls.

CHANGES.md, Cargo.toml
Just a patch bump for @lnicola's bug fix.
The fix was entirely within proj, so there's no need for a proj-sys release.
=> proj 0.25.1 release

Cargo.toml, proj-sys/build.rs, src/geo_types.rs, src/lib.rs, src/proj.rs, src/transform.rs
Fixes #101, #108
An alternative to #106, but as proposed in #108, I've done so by porting the [Transform trait from geo](https://github.com/georust/geo/pull/718 ) to proj so that we won't need similar-but-different code in two places.
I chose to double down on a trait-based approach since it seemed idiomatic to our other georust code. However, like proposed in #106, I leveraged proj_array in more places.
/cc @x4d3 
corresponding PRs:
- https://github.com/georust/geo/pull/730
- https://github.com/frewsxcv/rgis/pull/47
=> Port transform trait from geo and add a mutable flavor

Cargo.toml, proj-sys/Cargo.toml
Upgrade all proj-sys and proj dependency versions to the latest. For consistency all versions are fully-specified. The only exception is the [approx](https://crates.io/crates/approx) lib because the trait is implemented upstream in `geo-types`. Perhaps if we change geo-types to use `approx = "*"`, it could work?
It is fairly easy to upgrade them now using [cargo upgrade](https://lib.rs/crates/cargo-edit). I usually run it in offline mode due to an [issue](https://github.com/killercup/cargo-edit/issues/515#issuecomment-996931030)
```
cargo update && cargo upgrade --offline --workspace
```
=> Upgrade dependencies except "approx"

README.md, src/lib.rs
Hi folks!
Great work with this bindings and the whole georust ecosystem.
In this PR I propose to add to both the readme and the lib.rs docstring a comment on how to transform structures from `geo-types`. It took me half an hour and digging into the issues to learn that was possible and how to do it, so not ideal. I would like to save someone the research time so they can focus on using this great project!
✌️
=> document the usage of Transform for types in geo-types

CHANGES.md, Cargo.toml
Anything else we should be waiting for before the 0.26.0 release?
@nyurik mentioned that releasing this makes some things simpler for them: https://github.com/georust/geo/pull/798#issuecomment-1100922099
=> Prepare for 0.26.0 release.

CHANGES.md, src/proj.rs
=> Return an error if a definition can't be retrieved

CHANGES.md, src/lib.rs, src/proj.rs
Note this PR targets your PR #133 @urschrei, and is a follow-up to this comment specifically: https://github.com/georust/proj/pull/133#discussion_r896109068
This proposal is an admittedly baroque dance, but I think it has some benefits...
If we were to just do the [Conventional re-naming for libproj entities](https://github.com/georust/proj/commit/ac63a9ecea3f3f4ce7c3bafea4fcec1a34432f0d) commit, legacy users of the `Info` trait would see an error like:
```
warning: unused import: `Info`
--> src/main.rs:1:18
|
1 | use proj::{Proj, Info};
|                  ^^^^
|
= note: `#[warn(unused_imports)]` on by default
error[E0599]: no method named `network_enabled` found for struct `Proj` in the current scope
--> src/main.rs:5:19
|
5   |     assert!(!proj.network_enabled());
| …
```
=> Idiomatic renaming of entities from libproj

src/lib.rs, src/proj.rs
Previously we'd made the struct public, but we also probably want to make it possible to *get* the struct (`pub fn proj_info`) and we also probably want to make the fields public, otherwise people can't do much with it.
I also tweaked the docs a bit to better disambiguate between `info` and `proj_info`.
=> make `fn proj_info` public

CHANGES.md, proj-sys/CHANGES.md, src/lib.rs, src/proj.rs
=> Make PjInfo struct public

CHANGES.md, Cargo.toml
We bumped the approx dep in geo-types a while back, we should do the
same here.
=> match approx spec to geo-types

CHANGES.md, Cargo.toml, proj-sys/CHANGES.md, proj-sys/Cargo.toml
Uses a SPDX license expression as recommended by [Cargo](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields).
This enables e.g. parsing via the [CycloneDX Rust Cargo Plugin](https://github.com/CycloneDX/cyclonedx-rust-cargo).
=> Use SPDX license expression

CHANGES.md, proj-sys/build.rs, src/network.rs, src/proj.rs
We're now denying some optional lints related to unsafe handling of raw pointers
=> Add pointer lints, run clippy, apply fixes

CHANGES.md, Cargo.toml, README.md, src/geo_types.rs, src/lib.rs
Also updates references to correct libproj version in docs
=> Update to geo-types 0.7.8

src/proj.rs
This adds a wrapper of `transform_bounds`, similar to pyproj's `transform_bounds` ([docs](https://pyproj4.github.io/pyproj/stable/api/proj.html#pyproj.Proj.transform_bounds), [code](https://github.com/pyproj4/pyproj/blob/79a8602a2b0b50bf72c072b5a31317570bbdf550/pyproj/_transformer.pyx#L935-L1018)). 
This also adds a quick doctest, which is derived from one of the above doctests, but which I ran in pyproj to get the output data to compare against.
```py
from pyproj import CRS, Transformer
start = CRS("EPSG:2230")
end = CRS("EPSG:26946")
transformer = Transformer.from_crs(start, end, always_xy=True)
transformer.transform_bounds(4760096.421921, 3744293.729449, 4760196.421921, 3744393.729449)
```
Questions:
- Should this handle radians/degrees like pyproj is doing?
=> Add `transform_bounds` to wrap `proj_trans_bounds`

src/lib.rs
Hopefully CI won't merge this.
Trying again after enabling "require status checks" in the protected branch settings.
=> Take #2: Add a failing test to check that merge queues work

src/lib.rs
Hopefully CI won't merge this.
This time I specified that the "ci result" task must complete before merging. Let's see if it works. 
If this hangs without merging, we still might need #170.
=> Add a failing test to check that merge queues work

.github/workflows/test.yml, src/lib.rs
Hopefully CI won't merge this. If it does, I'll revert it right away.
I'm starting to suspect that the issue is with our aggregate "ci status" job. Previously the ci status job was skipped if one of it's dependents failed. It seems like maybe "skipped" doesn't count as "failed"?
=>  Add a failing test to check that merge queues work

proj-sys/build.rs
Unpacking the proj source code to the cargo registry cache can run into potential data races for concurrent builds. This can be fixed by unpacking the source code into the build directory of the current build. This also ensures that we don't infer with a otherwise assumed static registry cache directory.
=> Fix a racecondition in unpacking proj-src

proj-sys/build.rs
We need to always build release builds there (to prevent linker errors due to mixing up debug and release runtimes) and we need an additional flag to prevent the static library to expect some proj.dll file to exist
=> Add bundling support on windows

Cargo.toml, src/network.rs, src/proj.rs
Addresses #189, reducing `cargo tree -F network | wc -l` from 296 to 190.
=> Port from reqwest to ureq

proj-sys/Cargo.toml
I've opted to allow several different versions there instead of just bumping the supported version as that makes it much easier to use proj-sys in a complex project where other crates depend on libpsqlite3-sys as well. Cargo then will figure out the right version for all dependencies as long as there is a overlapping version.
=> Allow to use different versions of the libsqlite3-sys crate

.github/workflows/test.yml, Cargo.toml, proj-sys/Cargo.toml
=> Update libsqlite3-sys to allow 0.31 as well

CHANGES.md, proj-sys/Cargo.toml
This commit increases the maximal supported libsqlite3-sys version to include 0.32 as well. It also fixes a warning about a unknown cfg by just adding it to the allow list as we set that via the build script.
---
=> Bump libsqlite3-sys to support version 0.32 as well

CHANGES.md, src/proj.rs
=> Add coordinate metadata creation and query functions

CHANGES.md, src/lib.rs, src/proj.rs
---
<s>Draft for now, </s>pls land #226 first.
=> Add method for epoch-enabled transformation pipeline

CHANGES.md, Cargo.toml, src/network.rs
---
<s>No changelog entry yet since we have other PRs in flight.</s>
This was an unfun piece of work as the ureq API has evolved significantly between 2.x and 3.0, and the way we're passing the connection pool object around is more difficult to do now. That having been said the tests pass and none of the changes affect the public API. We also have a new optional dep in the form of `http`, but I suspect it was present previously anyway.
=> Update network (grid download) functionality to use ureq 3.x

CHANGES.md, Cargo.toml, README.md, proj-sys/CHANGES.md, proj-sys/Cargo.toml, src/lib.rs
---
This updates libproj to v9.6.0, and bumps the `proj` MSRV to 1.82 (released 6 months ago)
I'd like to release these tomorrow (2025-04-18).
=> Prepare for proj-sys v0.26.0 and proj v0.30.0 release

CHANGES.md, src/lib.rs, src/proj.rs
---
This adds support for [as_wkt](https://proj.org/en/stable/development/reference/functions.html#c.proj_as_wkt) method and all its options
=> Adds an as_wkt() method on Proj

CHANGES.md, Cargo.toml
Incorporating proj-sys 0.27.0 (libproj 9.6.2)
---
=> Prepare for 0.31.0 release
